# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20160417_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='music_file',
            field=models.FileField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.Album'),
        ),
    ]
